/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.projects.hms.view;

import cse.projects.hms.controller.UserController;
import cse.projects.hms.view.CheckInScreen;
import javax.swing.JOptionPane;

/**
 *
 * @author ij944
 */
public class MainScreen extends javax.swing.JFrame {

    UserController userController = UserController.getInstance();

    /**
     * Creates new form MainFrame
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTT_reservation = new javax.swing.JButton();
        BUTT_reservationview = new javax.swing.JButton();
        BUTT_service = new javax.swing.JButton();
        BUTT_checkin = new javax.swing.JButton();
        BUTT_checkout = new javax.swing.JButton();
        BUTT_management = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BUTT_reservation.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_reservation.setText("예약");
        BUTT_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_reservationActionPerformed(evt);
            }
        });

        BUTT_reservationview.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_reservationview.setText("예약조회");
        BUTT_reservationview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_reservationviewActionPerformed(evt);
            }
        });

        BUTT_service.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_service.setText("룸서비스");
        BUTT_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_serviceActionPerformed(evt);
            }
        });

        BUTT_checkin.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_checkin.setText("체크인");
        BUTT_checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_checkinActionPerformed(evt);
            }
        });

        BUTT_checkout.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_checkout.setText("체크아웃");
        BUTT_checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_checkoutActionPerformed(evt);
            }
        });

        BUTT_management.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_management.setText("관리");
        BUTT_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_managementActionPerformed(evt);
            }
        });

        logOutBtn.setText("로그아웃");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTT_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTT_reservationview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTT_service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_management, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logOutBtn)
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTT_service, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_reservationview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTT_checkin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_checkout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTT_management, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTT_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_reservationActionPerformed
        RoomScreen reservation = new RoomScreen();
        reservation.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_reservationActionPerformed

    private void BUTT_reservationviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_reservationviewActionPerformed
        // TODO add your handling code here:
        ReservationCheckScreen reservaioncheck = new ReservationCheckScreen();
        reservaioncheck.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_reservationviewActionPerformed

    private void BUTT_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_serviceActionPerformed
        // TODO add your handling code here:
        RoomServiceScreen roomservicescreen = new RoomServiceScreen();
        roomservicescreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_serviceActionPerformed

    private void BUTT_checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_checkinActionPerformed
        // TODO add your handling code here:
        CheckInScreen checkinscreen = new CheckInScreen();
        checkinscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_checkinActionPerformed

    private void BUTT_checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_checkoutActionPerformed
        // TODO add your handling code here:
        CheckOutScreen checkoutscreen = new CheckOutScreen();
        checkoutscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_checkoutActionPerformed

    private void BUTT_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_managementActionPerformed
        JOptionPane aa = new JOptionPane();
        ManagementScreen managementscreen = new ManagementScreen();
        System.out.println("mainscreen UserController : " + userController.getUserType());
        if (userController.getUserType().equals("manager")) {
            managementscreen.setVisible(true);
            dispose();
        } else {
            aa.showMessageDialog(null, "관리자가 아닌 다른 사용자는 사용이 제한됩니다.");
        }
    }//GEN-LAST:event_BUTT_managementActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTT_checkin;
    private javax.swing.JButton BUTT_checkout;
    private javax.swing.JButton BUTT_management;
    private javax.swing.JButton BUTT_reservation;
    private javax.swing.JButton BUTT_reservationview;
    private javax.swing.JButton BUTT_service;
    private javax.swing.JButton logOutBtn;
    // End of variables declaration//GEN-END:variables
}
