/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cse.projects.hms.view;

import cse.projects.hms.controller.UserController;
import cse.projects.hms.dao.user.UserDao;
import javax.swing.JOptionPane;

/**
 *
 * @author 재진
 */
public class RegisterScreen extends javax.swing.JFrame {
    private UserDao userDao;
    private UserController userController = UserController.getInstance();
    private boolean isOkId = false;
    private boolean isOkPw= false;
    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idCheck = new javax.swing.JButton();
        pwCheck = new javax.swing.JButton();
        checkPwField = new javax.swing.JPasswordField();
        pwField = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        goback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 48)); // NOI18N
        jLabel1.setText("Register");

        jLabel2.setText("ID :");

        jLabel3.setText("CheckPassword :");

        jLabel4.setText("Password :");

        idCheck.setText("중복확인");
        idCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCheckActionPerformed(evt);
            }
        });

        pwCheck.setText("비밀번호 확인");
        pwCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwCheckActionPerformed(evt);
            }
        });

        register.setText("사용자 등록");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        goback.setText("goback");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idField)
                            .addComponent(checkPwField)
                            .addComponent(pwField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(idCheck))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(pwCheck))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(register)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(goback)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goback))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(idCheck))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwCheck)
                    .addComponent(checkPwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(register)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCheckActionPerformed
        // TODO add your handling code here:
        String inputId = idField.getText();
        
        if (userDao.findById(inputId)==true) {
            JOptionPane.showMessageDialog(null, "이미 존재하는 아이디입니다.");
        }
        else {
            JOptionPane.showMessageDialog(null, "사용 가능한 아이디입니다.");
            isOkId = true;
        }
    }//GEN-LAST:event_idCheckActionPerformed

    private void pwCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwCheckActionPerformed
        // TODO add your handling code here:
        String inputPw = "";
        String checkPw = "";
        char[] secretPw = pwField.getPassword(); // 입력한 PW
        for(char cha : secretPw){
            Character.toString(cha); // cha 에 저장된 값 string으로 변환
            inputPw += (inputPw.equals("")) ? ""+cha+"" : ""+cha+"";
        }
        
        char[] secretCheckPw = checkPwField.getPassword();
        for(char cha : secretCheckPw){
            Character.toString(cha); // cha 에 저장된 값 string으로 변환
            checkPw += (inputPw.equals("")) ? ""+cha+"" : ""+cha+"";
        }
        
        if(inputPw.equals(checkPw)) {
            JOptionPane.showMessageDialog(null, "비밀번호가 일치합니다");
            isOkPw = true;
        }
        else {
            JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다.");
        }
    }//GEN-LAST:event_pwCheckActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        String inputId = idField.getText();
        String inputPw = "";
        
        char[] secretPw = pwField.getPassword(); // 입력한 PW
        for(char cha : secretPw){
            Character.toString(cha); // cha 에 저장된 값 string으로 변환
            inputPw += (inputPw.equals("")) ? ""+cha+"" : ""+cha+"";
        }
        
        if((isOkId == true && isOkPw == true)){
            if(userController.isRegister(inputId,inputPw)){
                JOptionPane.showMessageDialog(null, "성공적으로 사용자 등록이 되었습니다.");
                
                // 여기에 화면 전환 함수.
            }
            else {
                JOptionPane.showMessageDialog(null, "등록에 오류가 발생했습니다.");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "아이디 중복확인 또는 비밀번호 확인을 해주세요.");
        }
    }//GEN-LAST:event_registerActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        // TODO add your handling code here:
        ManagementScreen managementscreen = new ManagementScreen();
        managementscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_gobackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField checkPwField;
    private javax.swing.JButton goback;
    private javax.swing.JButton idCheck;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton pwCheck;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
