/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse.projects.hms.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JRadioButton;

/**
 *
 * @author ij944
 */
public class RoomScreen extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public RoomScreen() {
        initComponents();
        setLocationRelativeTo(null);
        //initializeRadioButtons();
    }
//     private void initializeRadioButtons() {
//        JRadioButton[] radiobutts = { BUTT_standard, BUTT_royal, BUTT_sweet, BUTT_royalsweet };
//        for (JRadioButton radiobutt : radiobutts) {
//            radiobutt.addActionListener(this);
//        }
//    }
//    @Override
//    public void actionPerformed(ActionEvent e) {
//        JRadioButton selectedRadioButton = (JRadioButton) e.getSource();
//        selectedButtonText = selectedRadioButton.getText();
//        //throw new UnsupportedOperationException("Not supported yet.");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTT_goback = new javax.swing.JButton();
        BUTT_standard = new javax.swing.JRadioButton();
        BUTT_royal = new javax.swing.JRadioButton();
        BUTT_sweet = new javax.swing.JRadioButton();
        BUTT_royalsweet = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BUTT_goback.setText("뒤로 가기");
        BUTT_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_gobackActionPerformed(evt);
            }
        });

        BUTT_standard.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_standard.setText("Standard");
        BUTT_standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_standardActionPerformed(evt);
            }
        });

        BUTT_royal.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_royal.setText("Royal");
        BUTT_royal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_royalActionPerformed(evt);
            }
        });

        BUTT_sweet.setFont(new java.awt.Font("굴림", 0, 24));
        BUTT_sweet.setText("Suite");
        BUTT_sweet.setToolTipText("");
        BUTT_sweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_sweetActionPerformed(evt);
            }
        });

        BUTT_royalsweet.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        BUTT_royalsweet.setText("RoyalSuite");
        BUTT_royalsweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTT_royalsweetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTT_royalsweet)
                    .addComponent(BUTT_sweet, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTT_royal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTT_standard, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(BUTT_goback)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(BUTT_goback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTT_standard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTT_royal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTT_sweet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTT_royalsweet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTT_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_gobackActionPerformed
        MainScreen mainscreen = new MainScreen();
        mainscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_gobackActionPerformed

    private void BUTT_sweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_sweetActionPerformed
        // TODO add your handling code here:
        SuiteScreen sweetscreen = new SuiteScreen();
        sweetscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_sweetActionPerformed

    private void BUTT_standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_standardActionPerformed
        StandardScreen standardscreen = new StandardScreen();
        standardscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_standardActionPerformed

    private void BUTT_royalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_royalActionPerformed
        RoyalScreen royalscreen = new RoyalScreen();
        royalscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_royalActionPerformed

    private void BUTT_royalsweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTT_royalsweetActionPerformed
        RoyalSuiteScreen royalsweetscreen = new RoyalSuiteScreen();
        royalsweetscreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_BUTT_royalsweetActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTT_goback;
    private javax.swing.JRadioButton BUTT_royal;
    private javax.swing.JRadioButton BUTT_royalsweet;
    private javax.swing.JRadioButton BUTT_standard;
    private javax.swing.JRadioButton BUTT_sweet;
    // End of variables declaration//GEN-END:variables

}
